//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int IdUsers { get; set; }
        public int IdTypeEq { get; set; }
        public System.DateTime DateReg { get; set; }
        public int IdStatus { get; set; }
        public string Comment { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual TypeEquipment TypeEquipment { get; set; }
        public virtual User User { get; set; }
    }
}
